apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    name: tif-new-project
  name: tif-new-project
spec:
  runPolicy: Serial
  source:
    git:
      uri: "https://github.com/dav1dli/new-project-jenkinspl.git"
    sourceSecret:
      name: "jenkins"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
