apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Container"
      default:
        cpu: "125m"
        memory: "256Mi"
      defaultRequest:
        cpu: "125m"
        memory: "256Mi"

