apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Container"
      default:
        cpu: "100m"
        memory: "819Mi"
      defaultRequest:
        cpu: "100m"
        memory: "819Mi"

