apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Container"
      default:
        cpu: "100m"
        memory: "200Mi"
      defaultRequest:
        cpu: "50m"
        memory: "100Mi"

