apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources-notterminating
  spec:
    hard:
      pods: "2"
      requests.cpu: 100m
      requests.memory: 256Mi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources-terminating
  spec:
    hard:
      pods: "5"
    scopes:
    - Terminating    
kind: List
