apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources-notterminating
  spec:
    hard:
      pods: "5"
      requests.cpu: 0.25
      requests.memory: 2Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources-terminating
  spec:
    hard:
      pods: 10
    scopes:
    - Terminating    
kind: List
