apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources-notterminating
  spec:
    hard:
      pods: 10
      requests.cpu: 0.5
      requests.memory: 4Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources-terminating
  spec:
    hard:
      pods: 20
    scopes:
    - Terminating
kind: List
