apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources-notterminating
  spec:
    hard:
      pods: ?
      requests.cpu: ?
      requests.memory: ?Mi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources-terminating
  spec:
    hard:
      pods: 10
    scopes:
    - Terminating    
kind: List
